#include "VGA.h"
#include <stdio.h>     
#include <stdlib.h>     
#include <time.h>
#include "Renderer.h"
#include "Sprite.h"
#include "Enemy.h"
#include "Owl.h"
#include "Spaceship.h"
#include "Projectile.h"



int PointInRectangle(int x,int y,int x1,int y1,int x2,int y2){
  	return ((( (x) >= (x1)) && ((y) >= (y1))) && (((x) <= (x2)) && ((y) <= (y2))));
}

int Collision(Sprite *s1, Sprite *s2)
{
	return (PointInRectangle(s1->x, s1->y, s2->x, s2->y, s2->x+s2->width, s2->y+s2->height) ||
		PointInRectangle(s1->x+s1->width, s1->y+s1->height, s2->x,s2->y, s2->x+s2->width, s2->y+s2->height) ||
		PointInRectangle(s1->x, s1->y+s1->height, s2->x, s2->y, s2->x+s2->width, s2->y+s2->height) ||
		PointInRectangle(s1->x+s1->width, s1->y, s2->x, s2->y, s2->x+s2->width, s2->y+s2->height));
}
unsigned char SpaceShip[] = {
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,RED,RED,BLACK,WHITE,WHITE,WHITE,WHITE,BLACK,RED,RED,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,RED,RED,BLACK,WHITE,WHITE,WHITE,WHITE,BLACK,RED,RED,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,WHITE,WHITE,BLACK,WHITE,WHITE,WHITE,WHITE,BLACK,WHITE,WHITE,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,WHITE,WHITE,BLACK,WHITE,RED,RED,WHITE,BLACK,WHITE,WHITE,BLACK,BLACK,BLACK,
RED,RED,BLACK,BLUE,BLUE,BLACK,WHITE,RED,RED,WHITE,BLACK,BLUE,BLUE,BLACK,RED,RED,
RED,RED,BLACK,BLUE,BLUE,BLACK,RED,RED,RED,RED,BLACK,BLUE,BLUE,BLACK,RED,RED,
WHITE,WHITE,BLACK,WHITE,WHITE,WHITE,RED,WHITE,WHITE,RED,WHITE,WHITE,WHITE,BLACK,WHITE,WHITE,
WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,RED,WHITE,WHITE,RED,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,
WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,
WHITE,WHITE,WHITE,WHITE,BLACK,RED,RED,WHITE,WHITE,RED,RED,BLACK,WHITE,WHITE,WHITE,WHITE,
WHITE,WHITE,WHITE,WHITE,BLACK,RED,RED,WHITE,WHITE,RED,RED,BLACK,WHITE,WHITE,WHITE,WHITE,
WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE
};

unsigned char uranus[] = {
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,YELLOW,YELLOW,YELLOW,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLACK,YELLOW,YELLOW,YELLOW,BLACK,BLACK,YELLOW,YELLOW,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLUE,BLUE,GREEN,GREEN,BLUE,GREEN,GREEN,GREEN,BLUE,BLUE,YELLOW,BLACK,BLACK,BLACK,YELLOW,YELLOW,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLUE,GREEN,GREEN,GREEN,BLUE,BLUE,GREEN,GREEN,GREEN,GREEN,GREEN,BLUE,BLACK,BLACK,YELLOW,YELLOW,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,BLUE,GREEN,GREEN,GREEN,GREEN,BLUE,GREEN,GREEN,GREEN,GREEN,GREEN,BLUE,BLUE,BLUE,BLACK,YELLOW,YELLOW,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,BLUE,GREEN,GREEN,GREEN,GREEN,GREEN,BLUE,GREEN,GREEN,GREEN,BLUE,BLUE,BLUE,GREEN,GREEN,YELLOW,YELLOW,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLUE,BLUE,GREEN,GREEN,GREEN,GREEN,GREEN,BLUE,BLUE,BLUE,BLUE,BLUE,GREEN,GREEN,GREEN,GREEN,YELLOW,YELLOW,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,YELLOW,YELLOW,BLUE,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLUE,GREEN,GREEN,GREEN,BLUE,BLUE,BLUE,BLUE,BLUE,GREEN,GREEN,GREEN,GREEN,YELLOW,YELLOW,YELLOW,YELLOW,BLUE,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLUE,GREEN,GREEN,GREEN,GREEN,BLUE,BLUE,BLUE,BLUE,GREEN,GREEN,GREEN,YELLOW,YELLOW,YELLOW,GREEN,GREEN,BLUE,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLUE,GREEN,GREEN,GREEN,BLUE,BLUE,GREEN,GREEN,BLUE,BLUE,GREEN,YELLOW,YELLOW,YELLOW,GREEN,GREEN,GREEN,BLUE,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLUE,GREEN,GREEN,GREEN,BLUE,GREEN,GREEN,GREEN,GREEN,BLUE,YELLOW,YELLOW,YELLOW,GREEN,GREEN,GREEN,GREEN,BLUE,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,BLUE,GREEN,BLUE,BLUE,GREEN,GREEN,GREEN,GREEN,YELLOW,YELLOW,YELLOW,GREEN,GREEN,GREEN,GREEN,BLUE,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,YELLOW,BLUE,BLUE,BLUE,GREEN,GREEN,GREEN,GREEN,YELLOW,YELLOW,YELLOW,BLUE,BLUE,GREEN,GREEN,GREEN,BLUE,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,YELLOW,YELLOW,YELLOW,BLUE,GREEN,GREEN,GREEN,GREEN,YELLOW,YELLOW,YELLOW,GREEN,GREEN,BLUE,GREEN,GREEN,BLUE,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,YELLOW,YELLOW,BLACK,BLACK,BLUE,GREEN,GREEN,YELLOW,YELLOW,YELLOW,GREEN,GREEN,GREEN,BLUE,GREEN,BLUE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,YELLOW,YELLOW,BLACK,BLACK,BLACK,BLACK,YELLOW,YELLOW,YELLOW,YELLOW,GREEN,GREEN,GREEN,GREEN,BLUE,BLUE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,YELLOW,YELLOW,BLACK,BLACK,YELLOW,YELLOW,YELLOW,YELLOW,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,YELLOW,YELLOW,YELLOW,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK
};

unsigned char uranusOnFire[] = {
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,YELLOW,YELLOW,YELLOW,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLACK,YELLOW,YELLOW,YELLOW,BLACK,BLACK,YELLOW,YELLOW,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLUE,BLUE,GREEN,GREEN,RED,GREEN,GREEN,GREEN,BLUE,BLUE,YELLOW,BLACK,BLACK,BLACK,YELLOW,YELLOW,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLUE,GREEN,GREEN,GREEN,RED,RED,GREEN,GREEN,GREEN,GREEN,GREEN,RED,BLACK,BLACK,YELLOW,YELLOW,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,BLUE,GREEN,GREEN,GREEN,GREEN,RED,GREEN,GREEN,GREEN,GREEN,GREEN,RED,RED,RED,BLACK,YELLOW,YELLOW,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,BLUE,GREEN,GREEN,GREEN,GREEN,GREEN,RED,GREEN,GREEN,GREEN,RED,RED,RED,GREEN,GREEN,YELLOW,YELLOW,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLUE,BLUE,GREEN,GREEN,GREEN,GREEN,GREEN,RED,RED,RED,RED,RED,GREEN,GREEN,GREEN,GREEN,YELLOW,YELLOW,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLUE,RED,RED,RED,RED,RED,RED,RED,RED,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,YELLOW,YELLOW,BLUE,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLUE,GREEN,GREEN,GREEN,RED,RED,RED,RED,RED,GREEN,GREEN,GREEN,GREEN,YELLOW,YELLOW,YELLOW,YELLOW,BLUE,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLUE,GREEN,GREEN,GREEN,GREEN,RED,RED,RED,RED,GREEN,GREEN,GREEN,YELLOW,YELLOW,YELLOW,GREEN,GREEN,BLUE,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLUE,GREEN,GREEN,GREEN,RED,RED,GREEN,GREEN,RED,RED,GREEN,YELLOW,YELLOW,YELLOW,GREEN,GREEN,GREEN,BLUE,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLUE,GREEN,GREEN,GREEN,RED,GREEN,GREEN,GREEN,GREEN,RED,YELLOW,YELLOW,YELLOW,GREEN,GREEN,GREEN,GREEN,BLUE,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,BLUE,GREEN,RED,RED,GREEN,GREEN,GREEN,GREEN,YELLOW,YELLOW,YELLOW,GREEN,GREEN,GREEN,GREEN,BLUE,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,YELLOW,BLUE,RED,RED,GREEN,GREEN,GREEN,GREEN,YELLOW,YELLOW,YELLOW,RED,RED,GREEN,GREEN,GREEN,BLUE,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,YELLOW,YELLOW,YELLOW,BLUE,GREEN,GREEN,GREEN,GREEN,YELLOW,YELLOW,YELLOW,GREEN,GREEN,RED,GREEN,GREEN,BLUE,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,YELLOW,YELLOW,BLACK,BLACK,BLUE,GREEN,GREEN,YELLOW,YELLOW,YELLOW,GREEN,GREEN,GREEN,RED,GREEN,BLUE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,YELLOW,YELLOW,BLACK,BLACK,BLACK,BLACK,YELLOW,YELLOW,YELLOW,YELLOW,GREEN,GREEN,GREEN,GREEN,BLUE,BLUE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,YELLOW,YELLOW,BLACK,BLACK,YELLOW,YELLOW,YELLOW,YELLOW,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,YELLOW,YELLOW,YELLOW,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK
};

unsigned char projectileOwl[] = {
BLACK,BLACK,BLACK,BLACK,BLACK,RED,RED,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,RED,RED,RED,RED,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,RED,RED,RED,RED,RED,RED,BLACK,BLACK,BLACK,
BLACK,BLACK,RED,RED,YELLOW,YELLOW,YELLOW,YELLOW,RED,RED,BLACK,BLACK,
BLACK,RED,RED,YELLOW,YELLOW,YELLOW,WHITE,WHITE,YELLOW,RED,RED,BLACK,
BLACK,RED,RED,YELLOW,YELLOW,YELLOW,WHITE,WHITE,YELLOW,RED,RED,BLACK,
BLACK,RED,RED,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,RED,RED,BLACK,
BLACK,RED,RED,RED,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,RED,RED,BLACK,
BLACK,BLACK,RED,RED,YELLOW,YELLOW,YELLOW,YELLOW,RED,RED,BLACK,BLACK,
BLACK,BLACK,BLACK,RED,RED,RED,RED,RED,RED,BLACK,BLACK,BLACK
};

unsigned char Player2[256] ;

unsigned char Heart[]=
{
    GREEN,GREEN,BLACK,BLACK,GREEN,BLACK,BLACK,GREEN,GREEN,
    GREEN,BLACK,RED,RED,BLACK,RED,RED,BLACK,GREEN,
    BLACK,RED,RED,RED,RED,RED,RED,RED,BLACK,
    BLACK,RED,RED,RED,RED,RED,RED,RED,BLACK,
    GREEN,BLACK,RED,RED,RED,RED,RED,BLACK,GREEN,
    GREEN,GREEN,BLACK,RED,RED,RED,BLACK,GREEN,GREEN,
    GREEN,GREEN,GREEN,BLACK,RED,BLACK,GREEN,GREEN,GREEN,
    GREEN,GREEN,GREEN,GREEN,BLACK,GREEN,GREEN,GREEN,GREEN,
};

unsigned char bee[] = {BLACK, BLUE, BLACK, BLACK,BLACK, BLACK, YELLOW, BLACK, BLACK,BLACK, BLACK,BLUE, BLACK,
                          BLACK, BLACK, BLUE, BLACK,YELLOW, RED, YELLOW, RED, YELLOW,BLACK, BLUE,BLACK, BLACK,
                          BLACK, BLACK, BLACK, BLUE,RED, RED, YELLOW, RED, RED,BLUE, BLACK,BLACK, BLACK,
                          BLACK, BLACK, BLACK, BLACK,YELLOW, YELLOW, YELLOW, YELLOW, YELLOW,BLACK, BLACK,BLACK, BLACK,
                          BLACK, BLACK, BLACK, BLUE,BLUE, YELLOW, YELLOW, YELLOW, BLUE,BLUE, BLACK,BLACK, BLACK,
                          BLACK, BLACK, BLUE, BLUE,BLUE, RED, RED, RED, BLUE,BLUE, BLUE,BLACK, BLACK,
                          BLACK, BLUE, BLUE, BLUE,BLACK, RED, RED, RED, BLACK,BLUE, BLUE,BLUE, BLACK,
                          BLUE, BLUE, BLUE, BLUE,BLACK, YELLOW, YELLOW, YELLOW, BLACK,BLUE, BLUE,BLUE, BLUE,
                          BLUE, BLUE, BLUE, BLACK,BLACK, RED, RED, RED, BLACK,BLACK, BLUE,BLUE, BLUE,
                          BLUE, BLUE, BLUE, BLACK,BLACK, BLACK, RED, BLACK, BLACK,BLACK, BLUE,BLUE, BLUE,};
                          
unsigned char enemySpaceship[] = {
BLACK,BLACK,YELLOW,YELLOW,BLACK,RED,RED,GREEN,GREEN,RED,RED,BLACK,YELLOW,YELLOW,BLACK,BLACK,
BLACK,GREEN,YELLOW,YELLOW,GREEN,RED,RED,GREEN,GREEN,RED,RED,GREEN,YELLOW,YELLOW,GREEN,BLACK,
BLACK,GREEN,YELLOW,YELLOW,GREEN,RED,RED,RED,RED,RED,RED,GREEN,YELLOW,YELLOW,GREEN,BLACK,
BLACK,GREEN,GREEN,GREEN,GREEN,RED,RED,RED,RED,RED,RED,GREEN,GREEN,GREEN,GREEN,BLACK,
BLACK,GREEN,GREEN,GREEN,GREEN,RED,RED,RED,RED,RED,RED,GREEN,GREEN,GREEN,GREEN,BLACK,
BLACK,GREEN,GREEN,GREEN,GREEN,RED,RED,RED,RED,RED,RED,GREEN,GREEN,GREEN,GREEN,BLACK,
BLACK,GREEN,GREEN,GREEN,GREEN,RED,RED,GREEN,GREEN,RED,RED,GREEN,GREEN,GREEN,GREEN,BLACK,
RED,RED,GREEN,BLACK,BLACK,RED,RED,GREEN,GREEN,RED,RED,BLACK,BLACK,GREEN,RED,RED,
RED,RED,RED,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,RED,RED,RED,
GREEN,RED,RED,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,RED,RED,GREEN,
GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,
GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,
GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,GREEN,YELLOW,YELLOW,GREEN,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,
GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,GREEN,YELLOW,YELLOW,GREEN,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,
GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,BLACK,YELLOW,YELLOW,BLACK,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,
GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN
};

unsigned char owl[] = {
BLACK,BLACK,BLACK,BLUE,BLUE,BLUE,BLACK,BLACK,BLACK,BLACK,BLUE,BLUE,BLUE,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,BLUE,BLUE,BLACK,BLACK,BLACK,BLACK,BLUE,BLUE,BLACK,BLACK,BLACK,BLACK,
BLUE,BLUE,BLUE,RED,RED,RED,BLUE,BLUE,BLUE,BLUE,RED,RED,RED,BLUE,BLUE,BLUE,
BLUE,BLUE,BLUE,RED,RED,RED,BLUE,BLUE,BLUE,BLUE,RED,RED,RED,BLUE,BLUE,BLUE,
BLACK,BLUE,BLUE,RED,RED,RED,BLUE,BLUE,BLUE,BLUE,RED,RED,RED,BLUE,BLUE,BLACK,
BLACK,BLACK,BLACK,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,BLUE,BLUE,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,
BLACK,BLACK,BLUE,GREEN,GREEN,GREEN,GREEN,BLUE,BLUE,GREEN,GREEN,GREEN,GREEN,BLUE,BLACK,BLACK,
BLACK,BLUE,BLUE,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLUE,BLUE,BLACK,
BLUE,BLUE,BLUE,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLUE,BLUE,BLUE,
BLUE,BLUE,BLUE,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLUE,BLUE,BLUE,
BLUE,BLUE,BLUE,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLUE,BLUE,BLUE,
BLUE,BLUE,BLUE,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLUE,BLUE,BLUE,
BLUE,BLUE,BLUE,BLACK,YELLOW,YELLOW,BLACK,BLACK,BLACK,BLACK,YELLOW,YELLOW,BLACK,BLUE,BLUE,BLUE,
BLACK,BLUE,BLUE,BLACK,YELLOW,YELLOW,BLACK,BLACK,BLACK,BLACK,YELLOW,YELLOW,BLACK,BLUE,BLUE,BLACK,
BLACK,BLACK,BLUE,BLACK,YELLOW,YELLOW,BLACK,BLACK,BLACK,BLACK,YELLOW,YELLOW,BLACK,BLUE,BLACK,BLACK,
};

unsigned char projectile[] = {BLACK, BLUE, BLACK,BLUE,BLUE,BLUE,BLUE,WHITE,BLUE,BLACK,RED,BLACK,BLACK,RED,BLACK,BLACK,RED,BLACK};


int gameState = 1;

Sprite enemies[10];
Enemy *bees[5];
Owl *owls[5];
int spawnTimer = 0;
int spawnTimerCooldown = (30*10);
Spaceship spaceship1(40,SpaceShip);
Spaceship spaceship2(100, Player2);
Renderer renderer;

//text
char zalagaText[] = "Zalaga";
char creditsText[] = "Credits";
char playGameText[] = "Play Game";

//screens
void mainMenu();
void credits();
void gameplay();
void gameOver();

Sprite* createEntity(int x, int y, char instanceOf)
{
    switch(instanceOf)
    {
      case 'B' :
        return new Enemy(x,y,bee);
        break;
      case 'O' :
        return new Owl(x,y,owl);
        break;
    }
}

void reactivateEntity(Sprite*sprite,int x, int y); 
 
void setup(){
  
  VGA.begin(VGAWISHBONESLOT(9),CHARMAPWISHBONESLOT(10));
  Serial.begin(9600);
  
  for(int i = 0; i<256; i++){
      if(SpaceShip[i] == WHITE)
        Player2[i] = RED;
      else if(SpaceShip[i] == RED)
        Player2[i] = BLUE;
      else if(SpaceShip[i] == BLUE)
        Player2[i] = YELLOW;
      else
        Player2[i] = SpaceShip[i];
  }
  for(int i = 0; i<5; i++){
    bees[i] = (Enemy*)createEntity(i*10,0,'B');
    owls[i] = (Owl*)createEntity(0,i*16,'O');
    owls[i]->initProjectile(projectileOwl);
  }
  spaceship1.initProjectiles(projectile);
  spaceship2.initProjectiles(projectile);
}
 

  void handleCollisions(int i);

void loop(){
  
  if(gameState == 0) 
    mainMenu();
  else if(gameState == 1) 
     gameplay();
  else if(gameState == 2)
    credits();
  else if(gameState == 3)
  {
    gameOver();
  }
  

}


 void handleCollisions(int i){
       int highscoreDelta = 1;
       if((Collision(&spaceship1, bees[i]) && bees[i]->active) || (Collision(&spaceship1, owls[i]->projectile) && owls[i]->projectile->active))
          spaceship1.active = false;
       if((Collision(&spaceship2, bees[i])&& bees[i]->active) || (Collision(&spaceship2,owls[i]->projectile)   && owls[i]->projectile->active))
          spaceship2.active = false;
       for(int j = 0; j<5; j++){
      if(spaceship1.projectiles[j]->active){
        if(Collision(spaceship1.projectiles[j],bees[i]) && bees[i]->active)
        {
          bees[i]->active = false;
          spaceship1.projectiles[j]->active = false;
          spaceship1.Score += highscoreDelta;
        }
        if(Collision(spaceship1.projectiles[j],owls[i]) && owls[i]->active)
        {
          owls[i]->active = false;
//          owls[i]->projectile->active = false;
          spaceship1.projectiles[j]->active = false;
          spaceship1.Score += highscoreDelta;
          
        }
      }
      if(spaceship2.projectiles[j]->active){
        if(Collision(spaceship2.projectiles[j],bees[i]) && bees[i]->active)
        {
          bees[i]->active = false;
          spaceship2.projectiles[j]->active = false;
          spaceship2.Score += highscoreDelta;
        }
        if(Collision(spaceship2.projectiles[j],owls[i]) && owls[i]->active)
        {
          owls[i]->active = false;
          spaceship2.projectiles[j]->active = false;
          spaceship2.Score += highscoreDelta;
        }
      }
    }
  }
  
  
void reactivateEntity(Sprite* sprite, int x, int y)
{
  sprite->active = true;
  sprite->x = x;
  sprite->y = y;
}

void mainMenu() {
  
  VGA.writeArea(20,20,24,24,uranus);
  
  
  VGA.printtext(60, 30,zalagaText);
  if(!digitalRead(FPGA_SW_0)){
    VGA.setColor(BLUE);
  }
  VGA.printtext(48,53, playGameText);
  VGA.setColor(WHITE);
  if(digitalRead(FPGA_SW_0)){
    VGA.setColor(BLUE);
  }
  VGA.printtext(55,73,creditsText);
  VGA.printtext(55,73,creditsText);
  VGA.printtext(55,73,creditsText);
  
  VGA.setColor(WHITE);
  if(digitalRead(FPGA_BTN_0))
    if(!digitalRead(FPGA_SW_0)){
      gameState = 1;
    }else
      gameState = 2;
}
      

void credits()
{
  VGA.setColor(WHITE);
  VGA.printtext(20, 25,"Alejandro Frech");
  VGA.printtext(20, 55,"Brandon Napky");
  VGA.printtext(20, 85,"Manuel Salguero");
  if(digitalRead(FPGA_BTN_1))
    gameState = 0;
}

void gameplay()
{  
    if(!spaceship1.active && !spaceship2.active){
      gameState = 3;
      VGA.clear();
      return;
    }
    VGA.clear();
    char scorePlayer1[4];
    char scorePlayer2[4];
    VGA.printtext(0, 0, "P1:");
    itoa(spaceship1.Score,scorePlayer1,10);
    VGA.printtext(30, 0, scorePlayer1);
    VGA.printtext(110, 0, "P2:");
    itoa(spaceship2.Score,scorePlayer2,10);
    VGA.printtext(140, 0, scorePlayer2);
    VGA.setColor(WHITE);
    
    spaceship1.move();
    spaceship2.move();
  
    for(int i = 0; i<5; i++){
      bees[i]->move();
      owls[i]->move();
      renderer.render(bees[i]);
      renderer.render(owls[i]);
      
      if(spawnTimer <= 0)
      {  
        int horizontalCoordinate = (rand() % (9) + 0);
        horizontalCoordinate*=16;
        int verticalCoordinate = rand() % 25 + 5;    
        if(!bees[i]->active){
          reactivateEntity(bees[i],horizontalCoordinate,verticalCoordinate);
          spawnTimer = spawnTimerCooldown;
        }
        if(!owls[i]->active){
          reactivateEntity(owls[i],horizontalCoordinate,verticalCoordinate);
          spawnTimer = spawnTimerCooldown;
        }
      }
          
    handleCollisions(i);
    spawnTimer--;  
    
    
    renderer.render(&spaceship1);
    renderer.render(&spaceship2);
    }
    delay(2);
    if(digitalRead(FPGA_BTN_1))
    {
      spaceship1.setMovement('r');
    }
    else if(digitalRead(FPGA_BTN_0))
      spaceship1.setMovement('l');
     else{
       spaceship1.movement = false;
     }
      
    if(digitalRead(FPGA_BTN_3))
      spaceship2.setMovement('r');
    else if(digitalRead(FPGA_BTN_2))
      spaceship2.setMovement('l');
      else{
       spaceship2.movement = false;
     }
    if(digitalRead(FPGA_SW_0)){
      spaceship1.shoot();
      
    }
    if(digitalRead(FPGA_SW_7)){
      spaceship2.shoot(); 
    }
    
    if(digitalRead(FPGA_SW_4) && digitalRead(FPGA_SW_5) && digitalRead(FPGA_SW_6)){
      spaceship2.active = true;
      spaceship1.active = true; 
      
      spaceship2.Score =0;
      spaceship1.Score =0;
    }
}

void gameOver()
{

   VGA.printtext(42, 30, "Game Over");
   VGA.setColor(RED);
   
   
     VGA.writeArea(65,55,24,24,uranusOnFire);
   
   if(spaceship1.Score>spaceship2.Score)
   {
     VGA.printtext(50,45,"P1 Wins");
     VGA.setColor(WHITE);
   }
   else if(spaceship1.Score<spaceship2.Score)
   {
     VGA.printtext(50,45,"P2 Wins");
     VGA.setColor(WHITE);
   }
   else
   {
      VGA.printtext(65,45,"Tie");
      VGA.setColor(WHITE);
   }
   if(digitalRead(FPGA_BTN_1))
   {
      gameState = 0;
      spaceship2.active = true;
      spaceship1.active = true; 

      spaceship2.Score =0;
      spaceship1.Score =0;
      
      spaceship1.x =40;      
      spaceship2.x =100;

     for(int i = 0; i<5; i++)
     {
        bees[i]->active = false;
        owls[i]->active = false;
        owls[i]->projectile->active=false;
     }
     VGA.clear();
   }
}

